vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        covers:
            uri_prefix: /covers
            upload_destination: '%kernel.project_dir%/public/covers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
